/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SENTRY - TYPE DEFINITIONS
 * The Deterministic Verification Engine
 * ═══════════════════════════════════════════════════════════════════════════
 */

// ─────────────────────────────────────────────────────────────────────────────
// COMPILER TYPES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Result of a compilation operation
 */
export interface CompilerResult {
    /** Whether the compilation succeeded */
    success: boolean;
    /** Combined stdout and stderr logs from forge */
    logs: string;
    /** Timestamp of compilation */
    timestamp: Date;
    /** Duration of compilation in milliseconds */
    durationMs?: number;
}

/**
 * Options for the compiler
 */
export interface CompilerOptions {
    /** Timeout in milliseconds for the forge build process */
    timeout?: number;
    /** Whether to clean before building */
    clean?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// SANITIZER TYPES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Result of sanitization operation
 */
export interface SanitizerResult {
    /** The sanitized code */
    code: string;
    /** List of imports that were remapped */
    remappedImports: ImportMapping[];
    /** List of imports that were removed */
    removedImports: string[];
    /** Whether the sanitization was successful */
    success: boolean;
}

/**
 * Mapping of an import from original to mocked version
 */
export interface ImportMapping {
    /** Original import path */
    original: string;
    /** Remapped mock import path */
    mocked: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// AI/AGENT TYPES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Hypothesis generated by the AI agent
 */
export interface VulnerabilityHypothesis {
    /** The target function name to attack */
    target: string;
    /** Type of vulnerability suspected */
    vulnerabilityType: 'ACCESS_CONTROL' | 'REENTRANCY' | 'OVERFLOW' | 'OTHER';
    /** Confidence score from 0-100 */
    confidence: number;
    /** Explanation of the suspected vulnerability */
    reasoning: string;
}

/**
 * AI Agent analysis request
 */
export interface AnalysisRequest {
    /** The Solidity source code to analyze */
    sourceCode: string;
    /** Contract name if known */
    contractName?: string;
}

/**
 * AI Agent analysis response
 */
export interface AnalysisResponse {
    /** List of vulnerability hypotheses */
    hypotheses: VulnerabilityHypothesis[];
    /** Whether analysis was successful */
    success: boolean;
    /** Error message if analysis failed */
    error?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// VERIFIER TYPES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Verdict from the verification engine
 */
export type Verdict =
    | 'CRITICAL_VULNERABILITY_FOUND'
    | 'VULNERABILITY_CONFIRMED'
    | 'FALSE_POSITIVE'
    | 'INCONCLUSIVE'
    | 'COMPILATION_FAILED';

/**
 * Result of exploit verification
 */
export interface VerificationResult {
    /** The final verdict */
    verdict: Verdict;
    /** The target function that was tested */
    targetFunction: string;
    /** Whether the exploit test passed (vulnerability exists) */
    exploitSucceeded: boolean;
    /** Raw forge test output */
    testOutput: string;
    /** Duration of test execution in ms */
    durationMs: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// PIPELINE TYPES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Full pipeline execution result
 */
export interface PipelineResult {
    /** Unique execution ID */
    executionId: string;
    /** Input source code */
    sourceCode: string;
    /** Sanitization result */
    sanitization: SanitizerResult;
    /** Compilation result */
    compilation: CompilerResult;
    /** Analysis result (if compilation succeeded) */
    analysis?: AnalysisResponse;
    /** Verification results (if analysis found targets) */
    verifications?: VerificationResult[];
    /** Overall pipeline status */
    status: 'SUCCESS' | 'COMPILATION_FAILED' | 'ANALYSIS_FAILED' | 'VERIFICATION_FAILED';
    /** Total execution time in ms */
    totalDurationMs: number;
}
